name: Build Dockerfile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: machine-learning-apps/gpr-docker-publish@master
      with:
        IMAGE_NAME: 'docker-actions-test'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
